### ISSUE TITLE
`simplejpeg` Incompatibility with `numpy` Version >= 2.0.0

### ISSUE THREAD

**Issue by abhiTronix** [jfolz/simplejpeg#2]
Hi @jfolz,

Thank you for this awesome library!

After testing, I found that the `simplejpeg` library is not compatible with the newer versions of `numpy` (>= 2.0.0). The recent changes in `numpy` have introduced modifications that cause issues with the `simplejpeg` Turbo C API. Currently, importing `simplejpeg` throws the following error:

```sh
>>> import simplejpeg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Abhishek Thakur\AppData\Roaming\Python\Python310\site-packages\simplejpeg\__init__.py", line 1, in <module>
    from ._jpeg import encode_jpeg
  File "simplejpeg\\_jpeg.pyx", line 1, in init simplejpeg._jpeg
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Could you please look into this issue and provide a fix as soon as possible?

Thanks!

**Comment by jfolz** [comment]
Looks like with NumPy 2.0, the ABI is now [backward rather than forward compatible](https://numpy.org/devdocs/dev/depending_on_numpy.html#adding-a-dependency-on-numpy). Meaning builds must now use `numpy>=2` rather than `oldest-supported-numpy`. That would mean dropping 3.8 (and of course 3.7), which I don't want to do at this point. So my plan is:

1. Release 1.7.3 built against `oldest-supported-numpy` with dependency `numpy<2`.
2. Release 1.7.4 built against `numpy>=2` and `requires-python>=3.7`

With this, there should be one final version with working wheels for 3.7 and 3.8, and newer builds will use the backwards-compatible ABI from thereon.

Annoyingly, it GitHub fails at downloading NumPy for 3.7 on Windows x64 right now:
https://github.com/jfolz/simplejpeg/actions/runs/9593793097/job/26454993372
https://github.com/jfolz/simplejpeg/actions/runs/9593793097/job/26456114385
https://github.com/jfolz/simplejpeg/actions/runs/9593793097/job/26457178022

**Comment by abhiTronix** [comment]
> So my plan is:
> 
> Release 1.7.3 built against oldest-supported-numpy with dependency numpy<2.
> Release 1.7.4 built against numpy>=2 and requires-python>=3.9

@jfolz  Your plan sounds solid. This way, there will be a final version with working wheels for Python 3.8, and future builds will utilize the backward-compatible ABI from `numpy>=2`.

> Annoyingly, it GitHub fails at downloading NumPy for 3.7 on Windows x64 right now:
> https://github.com/jfolz/simplejpeg/actions/runs/9593793097/job/26454993372
> https://github.com/jfolz/simplejpeg/actions/runs/9593793097/job/26456114385
> https://github.com/jfolz/simplejpeg/actions/runs/9593793097/job/26457178022

@jfolz I think you should drop support for [Python 3.7 makes sense since it reached its end-of-life on June 27, 2023 last year](https://endoflife.date/python). This would streamline the maintenance and allow you to focus on more recent versions.

**Comment by abhiTronix** [comment]
@jfolz Sorry closed by mistake.

**Comment by jfolz** [comment]
After a while, GitHub remembered how to download a file. 1.7.3 and 1.7.4 are now on PyPI. Please let me know if there are any issues with these versions.

**Comment by abhiTronix** [comment]
Kudos 🥳 Thanks for the quick fix.

**Comment by abhiTronix** [comment]
**This issue is fixed with [`simplejpeg` version `1.74`](https://pypi.org/project/simplejpeg/1.7.4/).**
